### ISSUE TITLE
Consumer MSK connectivity 

### ISSUE THREAD

**Issue by Sovenique** [jaehyeon-kim/kafka-pocs#3]
Hello,

When I try to use [consumer.py](https://github.com/jaehyeon-kim/kafka-pocs/blob/main/kafka-dev-with-docker/part-07/consumer.py) against an MSK cluster I get:

```
INFO:botocore.credentials:Found credentials in environment variables.
INFO:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connecting> [IPv4 ([REDACTED], 9198)]>: connecting to [REDACTED]:9198
INFO:kafka.conn:Probing node bootstrap-1 broker version
INFO:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connecting> [IPv4 ([REDACTED], 9198)]>: Connection complete.
ERROR:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connected> [IPv4 ([REDACTED], 9198)]>: socket disconnected
INFO:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connected> [IPv4 ([REDACTED], 9198)]>: Closing connection. KafkaConnectionError: socket disconnected
INFO:kafka.conn:Broker is not v(0, 10) -- it did not recognize ApiVersionRequest_v0
INFO:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connecting> [IPv4 ([REDACTED], 9198)]>: connecting to [REDACTED]:9198
INFO:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connecting> [IPv4 ([REDACTED], 9198)]>: Connection complete.
ERROR:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connected> [IPv4 ([REDACTED], 9198)]>: socket disconnected
INFO:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connected> [IPv4 ([REDACTED], 9198)]>: Closing connection. KafkaConnectionError: socket disconnected
INFO:kafka.conn:Broker is not v(0, 9) -- it did not recognize ListGroupsRequest_v0
INFO:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connecting> [IPv4 ([REDACTED], 9198)]>: connecting to [REDACTED]:9198
INFO:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connecting> [IPv4 ([REDACTED], 9198)]>: Connection complete.
ERROR:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connected> [IPv4 ([REDACTED], 9198)]>: socket disconnected
INFO:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connected> [IPv4 ([REDACTED], 9198)]>: Closing connection. KafkaConnectionError: socket disconnected
INFO:kafka.conn:Broker is not v(0, 8, 2) -- it did not recognize GroupCoordinatorRequest_v0
INFO:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connecting> [IPv4 ([REDACTED], 9198)]>: connecting to [REDACTED]:9198
INFO:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connecting> [IPv4 ([REDACTED], 9198)]>: Connection complete.
ERROR:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connected> [IPv4 ([REDACTED], 9198)]>: socket disconnected
INFO:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connected> [IPv4 ([REDACTED], 9198)]>: Closing connection. KafkaConnectionError: socket disconnected
INFO:kafka.conn:Broker is not v(0, 8, 1) -- it did not recognize OffsetFetchRequest_v0
INFO:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connecting> [IPv4 ([REDACTED], 9198)]>: connecting to [REDACTED]:9198
INFO:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connecting> [IPv4 ([REDACTED], 9198)]>: Connection complete.
ERROR:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connected> [IPv4 ([REDACTED], 9198)]>: socket disconnected
INFO:kafka.conn:<BrokerConnection node_id=bootstrap-1 host=[REDACTED]:9198 <connected> [IPv4 ([REDACTED], 9198)]>: Closing connection. KafkaConnectionError: socket disconnected
INFO:kafka.conn:Broker is not v(0, 8, 0) -- it did not recognize MetadataRequest_v0
Traceback (most recent call last):
  File "/home/appuser/aws-glue-schema-registry/serializer-deserializer-msk-iam/target/test.py", line 62, in <module>
    consumer = Consumer(
  File "/home/appuser/aws-glue-schema-registry/serializer-deserializer-msk-iam/target/test.py", line 23, in __init__
    self.consumer = self.create()
  File "/home/appuser/aws-glue-schema-registry/serializer-deserializer-msk-iam/target/test.py", line 31, in create
    return KafkaConsumer(
  File "/usr/local/lib/python3.9/site-packages/kafka/consumer/group.py", line 356, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/usr/local/lib/python3.9/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/usr/local/lib/python3.9/site-packages/kafka/client_async.py", line 909, in check_version
    version = conn.check_version(timeout=remaining, strict=strict, topics=list(self.config['bootstrap_topics_filter']))
  File "/usr/local/lib/python3.9/site-packages/kafka/conn.py", line 1297, in check_version
    raise Errors.UnrecognizedBrokerVersion()
kafka.errors.UnrecognizedBrokerVersion: UnrecognizedBrokerVersion
```
All ENV vars are exported properly.
Netcat works from the same environment against those brokers.

In the same fashion, I experienced the same issue with kafka-connect image, and I resolved it by introducing the `security.protocol=SASL_SSL`. 

Not sure what's the case here, any insights?

Thank you so much!

**Comment by jaehyeon-kim** [comment]
Hello,

The series rely on a Kafka cluster deployed locally using Docker and I haven't tested it against MSK. For your case, can you specify `api_version` in *KafkaConsumer* explicitly? For example, if I use MSK with Kafka version 2.8.1, I'll add `api_version = (2,8,1)`. See the kafka-python [documentation](https://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html) for details.

Cheers,
Jaehyeon

**Comment by Sovenique** [comment]
Hey,

Thank you so much for replying, yes I did try with `api_version = (2,8,1)`.

Although the `INFO:kafka.conn:Broker is not v(0, 8, 1) -- it did not recognize OffsetFetchRequest_v0` is now gone, I'm still getting the same socket disconnecting thing. 

This is indeed MSK related, so this issue is out of scope. 

Closing it, more insights are welcomed.

Cheers,
Sovenique
